name: CI
on:
  push:
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: 'test Base Path'
        run: pwd
      - name: 'show files inside'
        run: ls -al
      # - name: Checkout code
      #   uses: actions/checkout@v2
      # - name: Cache dependencies
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.composer/cache/files
      #     key: dependencies-composer-${{ hashFiles('composer.json') }}
      # - name: Setup PHP
      #   uses: shivammathur/setup-php@v2
      #   with:
      #     php-version: 8.0
      #     extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
      #     coverage: none
      # - name: Install Composer dependencies
      #   run: composer install --prefer-dist --no-interaction --no-suggest
      # - name: Install NPM dependencies
      #   run: npm install
      # - name: Compile assets
      #   run: npm run build
      # - name: Execute tests
      #   run: php artisan test
