name: CI
on:
  push:
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: 'test Base Path'
        run: pwd
      - name: 'show files inside'
        run: ls -al
      - name: Checkout code
        uses: actions/checkout@v3
       #- name: Cache dependencies
      - name: 'test Base Path'
        run: pwd
      - name: 'show files inside'
        run: ls -al
      - name: 'create test file'
        run: 'touch .github/test.md'
      - name: GIT Commit Build Artifacts (coverage, dist, devdist, docs)
        # Only run on main branch push (e.g. after pull request merge).
        if: github.event_name == 'push'
        run: |
          git config --global user.name "XGEN BOT"
          git config --global user.email "aquzif@users.noreply.github.com"
          git commit -a -m "CREATING REPOSITORY"
          git push
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.composer/cache/files
      #     key: dependencies-composer-${{ hashFiles('composer.json') }}
      # - name: Setup PHP
      #   uses: shivammathur/setup-php@v2
      #   with:
      #     php-version: 8.0
      #     extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
      #     coverage: none
      # - name: Install Composer dependencies
      #   run: composer install --prefer-dist --no-interaction --no-suggest
      # - name: Install NPM dependencies
      #   run: npm install
      # - name: Compile assets
      #   run: npm run build
      # - name: Execute tests
      #   run: php artisan test
